### ISSUE TITLE
jest-haste-map: @providesModule naming collision: Duplicate module name: react-native

### ISSUE THREAD

**Issue by MontoyaAndres** [Fried-Chicken/expo-monorepo#9]
I don't know if I'm the only one with this error, but it's terrible I cannot continue working and I don't know if you can help me with it.

I've been following this `expo-monorepo` to configure it with [this](https://github.com/MontoyaAndres/fullstack-graphql-airbnb-clone) project, in the [packages/app/](https://github.com/MontoyaAndres/fullstack-graphql-airbnb-clone/tree/master/packages/app) route, you can find all the React-Native code.

The error is this:

```
(node:22476) UnhandledPromiseRejectionWarning: Error: jest-haste-map: @providesModule naming collision:
  Duplicate module name: react-native
  Paths: /home/andres/Documents/fullstack-graphql-airbnb-clone/node_modules/react-native/package.json collides with /home/andres/Documents/fullstack-graphql-airbnb-clone/packages/app/node_modules/react-native/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at setModule (/home/andres/Documents/fullstack-graphql-airbnb-clone/node_modules/metro/node_modules/jest-haste-map/build/index.js:462:17)
    at workerReply (/home/andres/Documents/fullstack-graphql-airbnb-clone/node_modules/metro/node_modules/jest-haste-map/build/index.js:512:9)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Promise.all (index 1020)

(node:22476) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:22476) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

First, I tried cleaning up the cache and watchman, with these commands:

**I'm using Linux Mint in its latest version**
```
# Restart watchman
echo 256 | sudo tee -a /proc/sys/fs/inotify/max_user_instances
echo 32768 | sudo tee -a /proc/sys/fs/inotify/max_queued_events
echo 65536 | sudo tee -a /proc/sys/fs/inotify/max_user_watches
watchman shutdown-server
watchman watch-del-all

# Then remove all the node_modules from the packages

# Then clean cache
yarn cache clean

# Then install everything from the route folder `packages/`
yarn install
```

Then, I published this [issue](https://spectrum.chat/expo/general/trying-to-use-yarn-workspaces-with-expo-yarn-workspaces~44eaee6c-d153-43b5-a1e2-3855c77fd43a) in the spectrum chat group of expo, and only one guy answered me, but the example that he gave me did not work...

I don't know how to resolve it, but I'd be thankfully with you if you know how :smiley:

**Comment by MontoyaAndres** [comment]
I've changed the version of expo 33, you should do it with this example too.

Also, I have another error with this version, I'm going to publish it in the spectrum chat group of expo, and see if they can help me,

thanks for making this example also!

If you are curious about the [issues](https://spectrum.chat/expo/general/expo-33-yarn-workspaces-callback-with-id-0-undefined-undefined-not-found~461eb338-a4b3-42e8-a181-3a905667a04f) I'm talking about
